/**
* This code was generated by v0 by Vercel.
* @see https://v0.dev/t/No1dHOwZzHr
* Documentation: https://v0.dev/docs#integrating-generated-code-into-your-nextjs-app
*/

/** Add fonts into your Next.js project:

import { Inter } from 'next/font/google'

inter({
  subsets: ['latin'],
  display: 'swap',
})

To read more about using these font, please visit the Next.js documentation:
- App Directory: https://nextjs.org/docs/app/building-your-application/optimizing/fonts
- Pages Directory: https://nextjs.org/docs/pages/building-your-application/optimizing/fonts
**/
import { Card, CardHeader, CardTitle, CardDescription, CardContent } from "@/components/ui/card"
import { Input } from "@/components/ui/input"
import { Button } from "@/components/ui/button"

export function updatedhomepage() {
  return (
    (<Card className="w-full max-w-3xl">
      <CardHeader>
        <CardTitle>Math Assignment Check</CardTitle>
        <CardDescription>Upload your answer key and test files to check your assignment.</CardDescription>
      </CardHeader>
      <CardContent className="grid gap-8">
        <div>
          <h3 className="text-lg font-semibold">Answer Key</h3>
          <p className="text-muted-foreground">Upload the answer key file for the assignment.</p>
          <div className="mt-4 flex items-center gap-2">
            <Input id="answerKey" type="file" />
            <Button>
              <UploadIcon className="mr-2 h-4 w-4" />
              Upload
            </Button>
          </div>
          <div className="mt-2 flex items-center gap-2 text-sm font-medium">
            <CircleCheckIcon className="h-4 w-4 text-green-500" />
            <span>Answer key uploaded successfully</span>
          </div>
        </div>
        <div>
          <h3 className="text-lg font-semibold">Test</h3>
          <p className="text-muted-foreground">Upload the test file for the assignment.</p>
          <div className="mt-4 flex items-center gap-2">
            <Input id="test" type="file" />
            <Button>
              <UploadIcon className="mr-2 h-4 w-4" />
              Upload
            </Button>
          </div>
          <div
            className="mt-2 flex items-center gap-2 text-sm font-medium text-muted-foreground">
            <CircleXIcon className="h-4 w-4 text-red-500" />
            <span>Test file not uploaded yet</span>
          </div>
        </div>
      </CardContent>
    </Card>)
  );
}

function CircleCheckIcon(props) {
  return (
    (<svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round">
      <circle cx="12" cy="12" r="10" />
      <path d="m9 12 2 2 4-4" />
    </svg>)
  );
}


function CircleXIcon(props) {
  return (
    (<svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round">
      <circle cx="12" cy="12" r="10" />
      <path d="m15 9-6 6" />
      <path d="m9 9 6 6" />
    </svg>)
  );
}


function UploadIcon(props) {
  return (
    (<svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round">
      <path d="M21 15v4a2 2 0 0 1-2 2H5a2 2 0 0 1-2-2v-4" />
      <polyline points="17 8 12 3 7 8" />
      <line x1="12" x2="12" y1="3" y2="15" />
    </svg>)
  );
}
