/**
* This code was generated by v0 by Vercel.
* @see https://v0.dev/t/3ZQku4dRChV
* Documentation: https://v0.dev/docs#integrating-generated-code-into-your-nextjs-app
*/

/** Add fonts into your Next.js project:

import { Inter } from 'next/font/google'

inter({
  subsets: ['latin'],
  display: 'swap',
})

To read more about using these font, please visit the Next.js documentation:
- App Directory: https://nextjs.org/docs/app/building-your-application/optimizing/fonts
- Pages Directory: https://nextjs.org/docs/pages/building-your-application/optimizing/fonts
**/
import { Textarea } from "@/components/ui/textarea"
import { Button } from "@/components/ui/button"

export function updatedAnswers() {
  return (
    (<div className="flex flex-col gap-8 w-full max-w-2xl mx-auto p-6">
      <div className="grid gap-4">
        <div className="flex flex-col gap-2">
          <h3 className="text-lg font-medium">What is the capital of France?</h3>
          <p className="text-sm text-muted-foreground">AI Generated Answer</p>
          <Textarea
            placeholder="Paris"
            className="rounded-md border border-input bg-transparent p-2 text-sm" />
          <div className="w-full">
            <Button size="sm" variant="outline" className="w-full">
              Edit
            </Button>
          </div>
        </div>
        <div className="flex flex-col gap-2">
          <h3 className="text-lg font-medium">Explain the concept of photosynthesis in simple terms.</h3>
          <p className="text-sm text-muted-foreground">AI Generated Answer</p>
          <Textarea
            placeholder="Photosynthesis is the process by which plants use sunlight, water, and carbon dioxide to create oxygen and energy in the form of sugar."
            className="rounded-md border border-input bg-transparent p-2 text-sm" />
          <div className="w-full">
            <Button size="sm" variant="outline" className="w-full">
              Edit
            </Button>
          </div>
        </div>
        <div className="flex flex-col gap-2">
          <h3 className="text-lg font-medium">What is the largest ocean in the world?</h3>
          <p className="text-sm text-muted-foreground">AI Generated Answer</p>
          <Textarea
            placeholder="The Pacific Ocean is the largest ocean in the world."
            className="rounded-md border border-input bg-transparent p-2 text-sm" />
          <div className="w-full">
            <Button size="sm" variant="outline" className="w-full">
              Edit
            </Button>
          </div>
        </div>
        <div className="flex flex-col gap-2">
          <h3 className="text-lg font-medium">Describe the difference between a mammal and a reptile.</h3>
          <p className="text-sm text-muted-foreground">AI Generated Answer</p>
          <Textarea
            placeholder="Mammals are warm-blooded animals that have hair and give birth to live young, while reptiles are cold-blooded animals that lay eggs and have scales."
            className="rounded-md border border-input bg-transparent p-2 text-sm" />
          <div className="w-full">
            <Button size="sm" variant="outline" className="w-full">
              Edit
            </Button>
          </div>
        </div>
        <div className="flex flex-col gap-2">
          <h3 className="text-lg font-medium">What is the formula for the area of a circle?</h3>
          <p className="text-sm text-muted-foreground">AI Generated Answer</p>
          <Textarea
            placeholder="The formula for the area of a circle is πr^2, where r is the radius of the circle."
            className="rounded-md border border-input bg-transparent p-2 text-sm" />
          <div className="w-full">
            <Button size="sm" variant="outline" className="w-full">
              Edit
            </Button>
          </div>
        </div>
      </div>
    </div>)
  );
}
